language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - 5.2

script: ./run-tests.sh ~/.phpenv/versions/$(phpenv version-name)

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq git-core

before_script:
    - git clone http://github.com/sstephenson/bats
    - bats/install.sh $HOME
    - export PATH=$HOME/bin:$HOME/libexec:$PATH
    - bats --version
